version: '3.8'

volumes:
  postgres-data:

services:
  app:
    image: "mcr.microsoft.com/vscode/devcontainers/python:3.10"
    command: sleep infinity
    volumes:
      - "../..:/workspaces:cached"
    env_file: ".env"

  db:
    image: "postgres"
    restart: unless-stopped
    env:
        POSTGRES_USER: "styx"
        POSTGRES_PASSWORD: "styx"
        POSTGRES_DB: "styx"
