version: '3.8'

volumes:
  postgres-data:

services:
  app:
    image: "mcr.microsoft.com/vscode/devcontainers/python"
    command: sleep infinity
    volumes:
      - "..:/workspace:cached"

  db:
    image: "postgres"
    restart: unless-stopped
    environment:
        POSTGRES_USER: "styx"
        POSTGRES_PASSWORD: "styx"
        POSTGRES_DB: "styx"
